// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package create_user_mock

import (
	"context"

	"github.com/kirillVladov/account-service/internal/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewAccountRepositoryMock creates a new instance of AccountRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepositoryMock {
	mock := &AccountRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountRepositoryMock is an autogenerated mock type for the AccountRepository type
type AccountRepositoryMock struct {
	mock.Mock
}

type AccountRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepositoryMock) EXPECT() *AccountRepositoryMock_Expecter {
	return &AccountRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type AccountRepositoryMock
func (_mock *AccountRepositoryMock) Create(ctx context.Context, account dto.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AccountRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account dto.Account
func (_e *AccountRepositoryMock_Expecter) Create(ctx interface{}, account interface{}) *AccountRepositoryMock_Create_Call {
	return &AccountRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *AccountRepositoryMock_Create_Call) Run(run func(ctx context.Context, account dto.Account)) *AccountRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.Account
		if args[1] != nil {
			arg1 = args[1].(dto.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountRepositoryMock_Create_Call) Return(err error) *AccountRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, account dto.Account) error) *AccountRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}
