// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package create_user_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIssuePairMock creates a new instance of IssuePairMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuePairMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssuePairMock {
	mock := &IssuePairMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IssuePairMock is an autogenerated mock type for the IssuePair type
type IssuePairMock struct {
	mock.Mock
}

type IssuePairMock_Expecter struct {
	mock *mock.Mock
}

func (_m *IssuePairMock) EXPECT() *IssuePairMock_Expecter {
	return &IssuePairMock_Expecter{mock: &_m.Mock}
}

// IssuePair provides a mock function for the type IssuePairMock
func (_mock *IssuePairMock) IssuePair(userID string, role string) (string, string, error) {
	ret := _mock.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for IssuePair")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, string, error)); ok {
		return returnFunc(userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = returnFunc(userID, role)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(userID, role)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// IssuePairMock_IssuePair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssuePair'
type IssuePairMock_IssuePair_Call struct {
	*mock.Call
}

// IssuePair is a helper method to define mock.On call
//   - userID string
//   - role string
func (_e *IssuePairMock_Expecter) IssuePair(userID interface{}, role interface{}) *IssuePairMock_IssuePair_Call {
	return &IssuePairMock_IssuePair_Call{Call: _e.mock.On("IssuePair", userID, role)}
}

func (_c *IssuePairMock_IssuePair_Call) Run(run func(userID string, role string)) *IssuePairMock_IssuePair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IssuePairMock_IssuePair_Call) Return(s string, s1 string, err error) *IssuePairMock_IssuePair_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *IssuePairMock_IssuePair_Call) RunAndReturn(run func(userID string, role string) (string, string, error)) *IssuePairMock_IssuePair_Call {
	_c.Call.Return(run)
	return _c
}
