// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package create_user_mock

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewTokensRepoMock creates a new instance of TokensRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokensRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokensRepoMock {
	mock := &TokensRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokensRepoMock is an autogenerated mock type for the TokensRepo type
type TokensRepoMock struct {
	mock.Mock
}

type TokensRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokensRepoMock) EXPECT() *TokensRepoMock_Expecter {
	return &TokensRepoMock_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function for the type TokensRepoMock
func (_mock *TokensRepoMock) CreateRefreshToken(ctx context.Context, userID uuid.UUID, organizationID int64, tokenHash string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, userID, organizationID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, organizationID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokensRepoMock_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type TokensRepoMock_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - organizationID int64
//   - tokenHash string
//   - expiresAt time.Time
func (_e *TokensRepoMock_Expecter) CreateRefreshToken(ctx interface{}, userID interface{}, organizationID interface{}, tokenHash interface{}, expiresAt interface{}) *TokensRepoMock_CreateRefreshToken_Call {
	return &TokensRepoMock_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, userID, organizationID, tokenHash, expiresAt)}
}

func (_c *TokensRepoMock_CreateRefreshToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, organizationID int64, tokenHash string, expiresAt time.Time)) *TokensRepoMock_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TokensRepoMock_CreateRefreshToken_Call) Return(err error) *TokensRepoMock_CreateRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokensRepoMock_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, organizationID int64, tokenHash string, expiresAt time.Time) error) *TokensRepoMock_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
