apiVersion: v2
name: account-service
description: A Helm chart for kirillVladov application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - go 
  - back
sources:
  - https://github.com/kirillVladov/account-service.git
maintainers:
  - name: kirillVladov