// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package get_user_mock

import (
	"context"

	"github.com/google/uuid"
	"github.com/kirillVladov/account-service/internal/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewAccountRepositoryMock creates a new instance of AccountRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepositoryMock {
	mock := &AccountRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountRepositoryMock is an autogenerated mock type for the AccountRepository type
type AccountRepositoryMock struct {
	mock.Mock
}

type AccountRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepositoryMock) EXPECT() *AccountRepositoryMock_Expecter {
	return &AccountRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type AccountRepositoryMock
func (_mock *AccountRepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (dto.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountRepositoryMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AccountRepositoryMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AccountRepositoryMock_Expecter) GetByID(ctx interface{}, id interface{}) *AccountRepositoryMock_GetByID_Call {
	return &AccountRepositoryMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AccountRepositoryMock_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AccountRepositoryMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountRepositoryMock_GetByID_Call) Return(account dto.Account, err error) *AccountRepositoryMock_GetByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountRepositoryMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (dto.Account, error)) *AccountRepositoryMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
