// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package get_by_telegram_id_mock

import (
	"context"

	"github.com/kirillVladov/account-service/internal/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// GetByTelegramID provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) GetByTelegramID(ctx context.Context, telegramID string) (dto.Account, error) {
	ret := _mock.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTelegramID")
	}

	var r0 dto.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (dto.Account, error)); ok {
		return returnFunc(ctx, telegramID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) dto.Account); ok {
		r0 = returnFunc(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(dto.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_GetByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTelegramID'
type RepositoryMock_GetByTelegramID_Call struct {
	*mock.Call
}

// GetByTelegramID is a helper method to define mock.On call
//   - ctx context.Context
//   - telegramID string
func (_e *RepositoryMock_Expecter) GetByTelegramID(ctx interface{}, telegramID interface{}) *RepositoryMock_GetByTelegramID_Call {
	return &RepositoryMock_GetByTelegramID_Call{Call: _e.mock.On("GetByTelegramID", ctx, telegramID)}
}

func (_c *RepositoryMock_GetByTelegramID_Call) Run(run func(ctx context.Context, telegramID string)) *RepositoryMock_GetByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryMock_GetByTelegramID_Call) Return(account dto.Account, err error) *RepositoryMock_GetByTelegramID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *RepositoryMock_GetByTelegramID_Call) RunAndReturn(run func(ctx context.Context, telegramID string) (dto.Account, error)) *RepositoryMock_GetByTelegramID_Call {
	_c.Call.Return(run)
	return _c
}
